In [ ]:
import numpy as np
from copy import deepcopy


In [ ]:
def sphere(x):
  total = 0
  for i in x:
    total += i*i
  return total

In [ ]:
def seq_cost(x):
  total = 0
  for i in range(5):
    total += (x[i] - (i+1))**2
  return total

In [ ]:
seq_cost([1,2,3,4,5])

0

In [ ]:
def costLP(v):
  if v[0] + v[1] + v[2] <10:  #x+y+z <10
    return 10000000
  if 2*v[1] +4*v[2] <25:  # 2y+4z<25
    return 10000000
  return 3*v[0] +4*v[1]+5*v[2]  #3x+4y+5z

In [ ]:
class problem:
  def __init__(self):
    self.number_of_genes = 3
    self.min_value = 0
    self.max_value = 50
    self.cost_function = costLP
    self.acceptable_cost = 0.00001
    pass

In [ ]:
class individual:
  def __init__(self, prob):
    self.chromosome = np.random.uniform(prob.min_value, prob.max_value, prob.number_of_genes)
    self.cost = prob.cost_function(self.chromosome)

  def mutate(self, rate_of_gene_mutation, range_of_gene_mutation):
    for index in range(len(self.chromosome)):
      if np.random.uniform() < rate_of_gene_mutation:
        self.chromosome[index] += np.random.randn()*range_of_gene_mutation

  def crossover(self,parent2, explore_crossover):
    alpha = np.random.uniform(-explore_crossover, 1+explore_crossover)
    child1 = deepcopy(self)
    child2 = deepcopy(parent2)
    child1.chromosome = alpha*self.chromosome + (1-alpha)*parent2.chromosome
    child2.chromosome = alpha*parent2.chromosome + (1-alpha)*self.chromosome
    return child1,child2


In [ ]:
class parameters:
  def __init__(self):
    self.population= 1000;
    self.birth_rate_per_generation = 1
    self.explore_crossover_range = 0.2
    self.gene_mutation_rate = 0.2
    self.gene_mutation_range = 0.5
    self.max_number_of_generations = 1000


In [ ]:
def choose_parents(population):
  index1 = np.random.randint(population)
  index2 = np.random.randint(population)
  if index1 == index2:
    return choose_parents(population)
  return index1,index2

In [ ]:
def run_genetic(prob, params):
  # read variables
  number_in_population = params.population
  rate_of_gene_mutation = params.gene_mutation_rate
  range_of_gene_mutation = params.gene_mutation_range
  explore_crossover = params.explore_crossover_range
  max_number_of_generations = params.max_number_of_generations
  cost_function = prob.cost_function
  acceptable_cost = prob.acceptable_cost
  number_of_children_per_generation =number_in_population * params.birth_rate_per_generation

  # Create our population
  population = []
  best_solution = individual(prob)
  best_solution.cost = np.infty

  for i in range(number_in_population):
    new_individual = individual(prob)
    if new_individual.cost < best_solution.cost:
      best_solution = deepcopy(new_individual)
    population.append(new_individual)

  print(len(population))

  # start loop
  for i in range(max_number_of_generations):
    children = []
      #choose parents
    while len(children) < number_of_children_per_generation:
      parent1_index, parent2_index = choose_parents(number_in_population)

      parent1 = population[parent1_index]
      parent2 = population[parent2_index]

        # create children
      child1, child2 = parent1.crossover(parent2,explore_crossover)
      child1.mutate(rate_of_gene_mutation,range_of_gene_mutation)
      child2.mutate(rate_of_gene_mutation,range_of_gene_mutation)
      child1.cost = cost_function(child1.chromosome)
      child2.cost = cost_function(child2.chromosome)
      children.append(child1)
      children.append(child2)

    population += children

      # sort population
    population = sorted(population, key=lambda x: x.cost)

      # cull population
    population = population[:number_in_population]
      #check solution
    if population[0].cost < best_solution.cost:
      best_solution = deepcopy(population[0])
      print(best_solution.cost)
    if best_solution.cost < acceptable_cost:
      break
  return population, best_solution




In [ ]:
p.number_of_genes

8

In [ ]:
prob = problem()
params = parameters()

In [ ]:
pop, best = run_genetic(prob, params)

1000
55.55062863537466
48.52317774454074
47.91017407019055
45.487684611902885
43.7049163333053
43.369019384553305
43.29781807373436
42.93820176351317
42.52819704686413
42.52006767538303
42.51980930580737
42.50811777121475
42.50648226986013
42.50290221389477
42.50157199679891
42.5002928605965
42.500023760027354
42.50000856697994
42.50000563243524
42.500000497700604
42.50000020490067
42.500000112212774
42.500000081045314
42.50000005663811
42.50000003741381
42.50000002913736
42.50000002830825
42.50000002829335
42.500000028248465
42.50000002793656
42.500000027784075
42.50000002775513
42.50000002769534
42.50000002762406
42.50000002753786
42.500000027489364
42.50000002747486
42.50000002746446
42.50000002746385
42.500000027462015
42.50000002745576
42.50000002745121
42.5000000274462
42.50000002744436
42.50000002744405
42.50000002744373
42.50000002744371
42.50000002744365
42.500000027443484
42.50000002744332
42.50000002744313
42.500000027443114
42.50000002744297
42.50000002744296
42.50000002744

In [ ]:
best.chromosome

array([-2.0096025 , 11.51920502,  0.49039749])

In [ ]:
best.cost/prob.acceptable_cost

19.2918951081048

In [ ]:
i1.mutate(0.5,2)

In [ ]:
i2.chromosome

array([ 0.81958589, -5.5818371 , -1.38125102,  3.31001204, -3.32800164,
       -6.72162076, -6.67719998, -5.11699217])

In [ ]:
c1,c2 = i1.crossover(i2,0.5)

In [ ]:
c1.chromosome

array([ 0.30617427, -5.65154596, -1.59334734,  2.50636585, -3.03011947,
       -6.07906206, -6.4122788 , -4.56575781])

In [ ]:
c2.chromosome

array([-6.17715884, -6.53182553, -4.27168764, -7.6420331 ,  0.73151974,
        2.03513313, -3.06686898,  2.3951988 ])

In [ ]:
c1.chromosome + c2.chromosome

array([ -5.87098457, -12.18337149,  -5.86503498,  -5.13566725,
        -2.29859974,  -4.04392893,  -9.47914777,  -2.17055901])

In [ ]:
i1.chromosome+i2.chromosome

array([ -5.87098457, -12.18337149,  -5.86503498,  -5.13566725,
        -2.29859974,  -4.04392893,  -9.47914777,  -2.17055901])

In [ ]:
population = []
for i in range(1000):
  population.append(individual(prob
                               ))

In [ ]:
choose_parents(population)

(120, 767)