<a href="https://colab.research.google.com/github/Robert-Sheehy/AI/blob/main/Genetic_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
ind1 = np.random.uniform(-10,10,8)

In [ ]:
ind2 = np.random.uniform(-10,10,8)

In [ ]:
ind1

array([ 5.83425885,  7.60732818, -7.40517012,  4.40086035,  5.40561485,
        6.96640011, -3.22194526,  1.47496185])

In [ ]:
ind2

array([-6.22096843, -5.74323921,  5.57045111, -9.40953841, -2.26375857,
       -0.72897733, -6.66513425, -0.40990001])

In [ ]:
sphere(ind1)

256.4219806958255

In [ ]:
sphere(ind2)

241.50262697873575

In [ ]:
def sphere(x):
  total = 0
  for i in x:
    total+= i**2

  return total

In [ ]:
class problem:
  def __init__(self):
    self.number_of_genes = 8
    self.max_value = 10
    self.min_value = -10
    self.cost_function = sphere

In [ ]:
sphere(x)

14

In [ ]:
np.random.uniform()

0.0186986448881461

In [ ]:
class individual:
  def __init__(self,prob):
    self.chromosome = np.random.uniform(prob.min_value, prob.max_value,prob.number_of_genes)
    self.cost = prob.cost_function(self.chromosome)

  def mutate(self, rate_of_gene_mutation,range_of_gene_mutation):
    for index in range(len(self.chromosome)):
      if  np.random.uniform() < rate_of_gene_mutation:
        self.chromosome[index] += np.random.randn() * range_of_gene_mutation

In [ ]:
p1=problem()


In [ ]:
p1.number_of_genes

8

In [ ]:
indX = individual(p1)

In [ ]:
indX.chromosome

array([ 7.55818063, -9.81586348,  6.24105835, -1.44405887,  7.9003502 ,
       -7.07911607,  9.04877641, -6.51348673])

In [ ]:
indX.cost

431.34866714789047

In [ ]:
indX.mutate(0.25,2)

In [ ]:
indX.chromosome

array([ 7.55818063, -9.81586348,  6.24105835, -1.44405887,  7.9003502 ,
       -8.28951581,  9.04877641, -6.51348673])